[package]
name = "handlebars-cli-ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = "0.2.9"
handlebars = "4.2.1"
serde_json = "1.0.75"
